{% set version = "1.4.2" %}

package:
  name: aiounittest
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/aiounittest/aiounittest-{{ version }}.tar.gz
  sha256: 1478ec8013c70046569cdc76d541083ca7da362e6513cf29c7ecb51330229bdb

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - wrapt

test:
  imports:
    - aiounittest
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kwarunek/aiounittest
  summary: Test asyncio code more easily.
  license: MIT
  license_file: LICENSE
  description: |
    The aiounittest is a helper library to ease of your pain (and boilerplate),
    when writing a test of the asynchronous code (asyncio). You can test:

    - synchronous code (same as the unittest.TestCase)
    - asynchronous code, it supports syntax with async/await (Python 3.5+) and
      asyncio.coroutine/yield from (Python 3.4)

    In the Python 3.8 (release note) and newer consider to use the
    unittest.IsolatedAsyncioTestCase. Builtin unittest module is now
    asyncio-featured.

extra:
  recipe-maintainers:
    - bollwyvl
