{% set name = "aiounittest" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiounittest-{{ version }}.tar.gz
  sha256: bf51a4a430d28b1a527abb0bea1465a3a36a2bbca13bf9b84e749985b4c5a788

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - wrapt

test:
  imports:
    - aiounittest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kwarunek/aiounittest
  summary: Test asyncio code more easily.
  license: MIT
  license_file: LICENSE
  description: |
    The aiounittest is a helper library to ease of your pain (and boilerplate),
    when writing a test of the asynchronous code (asyncio). You can test:

    - synchronous code (same as the unittest.TestCase)
    - asynchronous code, it supports syntax with async/await (Python 3.5+) and
      asyncio.coroutine/yield from (Python 3.4)

    In the Python 3.8 (release note) and newer consider to use the
    unittest.IsolatedAsyncioTestCase. Builtin unittest module is now
    asyncio-featured.

extra:
  recipe-maintainers:
    - bollwyvl
