# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.4.3"

package:
  name: aiounittest
  version: ${{ version }}

source:
  - url: https://pypi.io/packages/source/a/aiounittest/aiounittest-${{ version }}.tar.gz
    sha256: dfe3af30aa0e08fa6c3a3621f78b0b2e5658fe56c370db709f002407a1027dbf
    target_directory: dist
  # TODO: maybe remove after https://github.com/kwarunek/aiounittest/pull/27
  - url: https://github.com/kwarunek/aiounittest/archive/refs/tags/${{ version }}.tar.gz
    sha256: 25752ec67087f5bd4af5d9ec10c9d7c0dbfe64820610f66044a2191c922d380b
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cp src/requirements.txt dist || copy src/requirements.txt dist
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - wrapt

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: aiounittest
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - cd src
      - coverage run --source=aiounittest --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=95

about:
  summary: Test asyncio code more easily.
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/kwarunek/aiounittest
  description: |
    The aiounittest is a helper library to ease of your pain (and boilerplate),
    when writing a test of the asynchronous code (asyncio). You can test:

    - synchronous code (same as the unittest.TestCase)
    - asynchronous code, it supports syntax with async/await (Python 3.5+) and
    asyncio.coroutine/yield from (Python 3.4)

    In the Python 3.8 (release note) and newer consider to use the
    unittest.IsolatedAsyncioTestCase. Builtin unittest module is now
    asyncio-featured.

extra:
  recipe-maintainers:
    - bollwyvl
